/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAbonnementRouteImport } from './routes/_authenticated/abonnement'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLocatairesRouteImport } from './routes/_authenticated/locataires'
import { Route as AuthenticatedLogementsRouteImport } from './routes/_authenticated/logements'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAbonnementsRouteImport } from './routes/_authenticated/admin.abonnements'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin.journal'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin.paiements'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedLocatairesTenantIdRouteImport } from './routes/_authenticated/locataires.$tenantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonnementRoute = AuthenticatedAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocatairesRoute = AuthenticatedLocatairesRouteImport.update({
  id: '/locataires',
  path: '/locataires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogementsRoute = AuthenticatedLogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAbonnementsRoute =
  AuthenticatedAdminAbonnementsRouteImport.update({
    id: '/abonnements',
    path: '/abonnements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLocatairesTenantIdRoute =
  AuthenticatedLocatairesTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AuthenticatedLocatairesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/locataires': typeof AuthenticatedLocatairesRouteWithChildren
  '/logements': typeof AuthenticatedLogementsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/locataires/$tenantId': typeof AuthenticatedLocatairesTenantIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/locataires': typeof AuthenticatedLocatairesRouteWithChildren
  '/logements': typeof AuthenticatedLogementsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/locataires/$tenantId': typeof AuthenticatedLocatairesTenantIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/abonnement': typeof AuthenticatedAbonnementRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/locataires': typeof AuthenticatedLocatairesRouteWithChildren
  '/_authenticated/logements': typeof AuthenticatedLogementsRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/locataires/$tenantId': typeof AuthenticatedLocatairesTenantIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/abonnement'
    | '/admin'
    | '/dashboard'
    | '/locataires'
    | '/logements'
    | '/paiements'
    | '/profil'
    | '/admin/abonnements'
    | '/admin/journal'
    | '/admin/paiements'
    | '/admin/utilisateurs'
    | '/locataires/$tenantId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/abonnement'
    | '/dashboard'
    | '/locataires'
    | '/logements'
    | '/paiements'
    | '/profil'
    | '/admin/abonnements'
    | '/admin/journal'
    | '/admin/paiements'
    | '/admin/utilisateurs'
    | '/locataires/$tenantId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/_authenticated/abonnement'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/locataires'
    | '/_authenticated/logements'
    | '/_authenticated/paiements'
    | '/_authenticated/profil'
    | '/_authenticated/admin/abonnements'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/locataires/$tenantId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonnement': {
      id: '/_authenticated/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AuthenticatedAbonnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locataires': {
      id: '/_authenticated/locataires'
      path: '/locataires'
      fullPath: '/locataires'
      preLoaderRoute: typeof AuthenticatedLocatairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logements': {
      id: '/_authenticated/logements'
      path: '/logements'
      fullPath: '/logements'
      preLoaderRoute: typeof AuthenticatedLogementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/abonnements': {
      id: '/_authenticated/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AuthenticatedAdminAbonnementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/locataires/$tenantId': {
      id: '/_authenticated/locataires/$tenantId'
      path: '/$tenantId'
      fullPath: '/locataires/$tenantId'
      preLoaderRoute: typeof AuthenticatedLocatairesTenantIdRouteImport
      parentRoute: typeof AuthenticatedLocatairesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAbonnementsRoute: typeof AuthenticatedAdminAbonnementsRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAbonnementsRoute: AuthenticatedAdminAbonnementsRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLocatairesRouteChildren {
  AuthenticatedLocatairesTenantIdRoute: typeof AuthenticatedLocatairesTenantIdRoute
}

const AuthenticatedLocatairesRouteChildren: AuthenticatedLocatairesRouteChildren =
  {
    AuthenticatedLocatairesTenantIdRoute: AuthenticatedLocatairesTenantIdRoute,
  }

const AuthenticatedLocatairesRouteWithChildren =
  AuthenticatedLocatairesRoute._addFileChildren(
    AuthenticatedLocatairesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonnementRoute: typeof AuthenticatedAbonnementRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLocatairesRoute: typeof AuthenticatedLocatairesRouteWithChildren
  AuthenticatedLogementsRoute: typeof AuthenticatedLogementsRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonnementRoute: AuthenticatedAbonnementRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLocatairesRoute: AuthenticatedLocatairesRouteWithChildren,
  AuthenticatedLogementsRoute: AuthenticatedLogementsRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
